import { useState } from 'react'
import { KeyRound, Lock, LockOpen, PenLine, ShieldCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Field, Select, Textarea } from '@/components/ui/fields'
import { Tabs } from '@/components/ui/tabs'
import { CopyButton } from '@/components/common/CopyButton'
import { DownloadButton } from '@/components/common/ActionButtons'
import { ErrorMessage, Notice } from '@/components/common/Feedback'
import { ToolActions, ToolInput, ToolOutput, ToolSection, ToolSettings } from '@/components/tool/parts'
import { useToolShortcuts } from '@/hooks/useShortcut'
import { generateRsaKeyPair, oaepMaxBytes, rsaOaepDecrypt, rsaOaepEncrypt, rsaSign, rsaVerify, type PemKeyPair, type RsaHash, type RsaSignScheme } from '@/lib/crypto/rsa'
import { errorMessage } from '@/lib/utils'

type TabId = 'generate' | 'encrypt' | 'decrypt' | 'sign' | 'verify'
const HASHES: RsaHash[] = ['SHA-256', 'SHA-384', 'SHA-512', 'SHA-1']
const hashOptions = HASHES.map((h) => ({ value: h, label: h }))

function KeyField({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (v: string) => void; placeholder: string }) {
  return <Field label={label} hint="PEM"><Textarea value={value} onChange={(e) => onChange(e.target.value)} rows={5} placeholder={placeholder} aria-label={label} className="text-xs" /></Field>
}

export default function RsaTool() {
  const [tab, setTab] = useState<TabId>('generate')
  const [bits, setBits] = useState('2048')
  const [purpose, setPurpose] = useState<'encrypt' | 'sign'>('encrypt')
  const [hash, setHash] = useState<RsaHash>('SHA-256')
  const [scheme, setScheme] = useState<RsaSignScheme>('RSA-PSS')
  const [pair, setPair] = useState<PemKeyPair | null>(null)
  const [pub, setPub] = useState('')
  const [priv, setPriv] = useState('')
  const [msg, setMsg] = useState('')
  const [sig, setSig] = useState('')
  const [result, setResult] = useState('')
  const [verdict, setVerdict] = useState<boolean | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)

  const reset = () => { setResult(''); setVerdict(null); setError(null) }
  const exec = async (fn: () => Promise<void>) => {
    setBusy(true); reset()
    try { await fn() } catch (e) {
      const m = errorMessage(e, 'Operation failed.')
      setError(/Failed to execute|DataError|OperationError|key/i.test(m) && !/Message is|at most|PEM/.test(m) ? `${m} Check that the key is a valid PEM, matches this operation and uses the same hash.` : m)
    } finally { setBusy(false) }
  }

  const generate = () => exec(async () => {
    const kp = await generateRsaKeyPair(purpose, Number(bits) as 2048 | 3072 | 4096, hash)
    setPair(kp); setPub(kp.publicPem); setPriv(kp.privatePem)
  })
  const clearAll = () => { setMsg(''); setSig(''); reset() }
  useToolShortcuts({ clear: clearAll })

  return (
    <>
      <Tabs label="RSA operation" value={tab} onChange={(t) => { setTab(t); reset() }} items={[
        { value: 'generate', label: 'Generate keys' }, { value: 'encrypt', label: 'Encrypt' }, { value: 'decrypt', label: 'Decrypt' }, { value: 'sign', label: 'Sign' }, { value: 'verify', label: 'Verify' }]} />

      {tab === 'generate' && (
        <>
          <Notice title="Key generation runs in your browser">Keys are generated by the Web Crypto API. Encryption keys (RSA-OAEP) and signing keys (RSA-PSS) are generated for one purpose each — use separate keys for separate jobs.</Notice>
          <ToolSettings>
            <Select label="Purpose" value={purpose} onChange={(v) => setPurpose(v as 'encrypt' | 'sign')} options={[{ value: 'encrypt', label: 'Encryption (RSA-OAEP)' }, { value: 'sign', label: 'Signing (RSA-PSS)' }]} className="w-56" />
            <Select label="Key size" value={bits} onChange={setBits} options={[{ value: '2048', label: '2048 bits' }, { value: '3072', label: '3072 bits' }, { value: '4096', label: '4096 bits (slow)' }]} className="w-40" />
            <Select label="Hash" value={hash} onChange={(v) => setHash(v as RsaHash)} options={hashOptions} className="w-36" />
          </ToolSettings>
          <ToolActions><Button variant="primary" onClick={generate} disabled={busy}><KeyRound /> {busy ? 'Generating…' : 'Generate key pair'}</Button></ToolActions>
          {error && <ErrorMessage title="Unable to generate keys">{error}</ErrorMessage>}
          {pair && (
            <div className="grid gap-4 lg:grid-cols-2">
              {([['Public key (SPKI PEM) — shareable', pair.publicPem, 'public.pem'], ['Private key (PKCS#8 PEM) — keep secret', pair.privatePem, 'private.pem']] as const).map(([title, pem, file]) => (
                <ToolSection key={file} title={title} actions={<><CopyButton value={pem} /><DownloadButton value={pem} filename={file} /></>}>
                  <pre tabIndex={0} className="max-h-64 overflow-auto rounded-md border border-input bg-background/60 p-3 font-mono text-[11px] leading-4">{pem}</pre>
                </ToolSection>
              ))}
            </div>
          )}
        </>
      )}

      {tab === 'encrypt' && (
        <>
          <Notice title="Encryption (public key)">Anyone with the public key can encrypt; only the private key can decrypt. Algorithm: RSA-OAEP. Output: Base64.</Notice>
          <KeyField label="Public key" value={pub} onChange={setPub} placeholder="-----BEGIN PUBLIC KEY-----" />
          <ToolSettings><Select label="OAEP hash" value={hash} onChange={(v) => setHash(v as RsaHash)} options={hashOptions} className="w-36" /><p className="pb-1 text-xs text-muted-foreground">Max message size for a 2048-bit key with {hash}: {oaepMaxBytes(2048, hash)} bytes.</p></ToolSettings>
          <ToolInput label="Message" value={msg} onChange={setMsg} rows={4} emptyHint="Type a short message to encrypt." mono={false} />
          <ToolActions><Button variant="primary" disabled={busy || !pub || !msg} onClick={() => exec(async () => setResult(await rsaOaepEncrypt(pub, hash, msg)))}><Lock /> Encrypt</Button></ToolActions>
          <ToolOutput label="Ciphertext (Base64)" value={result} error={error} errorTitle="Unable to encrypt" onClear={reset} wrapLong filename="ciphertext.txt" />
        </>
      )}

      {tab === 'decrypt' && (
        <>
          <Notice title="Decryption (private key)">Only the private key that matches the public key used to encrypt can decrypt. The hash must match the one used for encryption.</Notice>
          <KeyField label="Private key" value={priv} onChange={setPriv} placeholder="-----BEGIN PRIVATE KEY-----" />
          <ToolSettings><Select label="OAEP hash" value={hash} onChange={(v) => setHash(v as RsaHash)} options={hashOptions} className="w-36" /></ToolSettings>
          <ToolInput label="Ciphertext (Base64)" value={msg} onChange={setMsg} rows={4} emptyHint="Paste Base64 ciphertext." />
          <ToolActions><Button variant="primary" disabled={busy || !priv || !msg} onClick={() => exec(async () => setResult(await rsaOaepDecrypt(priv, hash, msg.trim())))}><LockOpen /> Decrypt</Button></ToolActions>
          <ToolOutput label="Plaintext" value={result} error={error} errorTitle="Unable to decrypt data" errorHints={['Incorrect private key', 'Different hash than used for encryption', 'Incorrect encoding', 'Altered ciphertext']} onClear={reset} wrapLong />
        </>
      )}

      {tab === 'sign' && (
        <>
          <Notice title="Signing (private key)">Signing proves who created a message and that it was not changed. It does <strong>not</strong> hide the message.</Notice>
          <KeyField label="Private key" value={priv} onChange={setPriv} placeholder="-----BEGIN PRIVATE KEY-----" />
          <ToolSettings>
            <Select label="Scheme" value={scheme} onChange={(v) => setScheme(v as RsaSignScheme)} options={[{ value: 'RSA-PSS', label: 'RSA-PSS (recommended)' }, { value: 'RSASSA-PKCS1-v1_5', label: 'RSASSA-PKCS1-v1_5' }]} className="w-56" />
            <Select label="Hash" value={hash} onChange={(v) => setHash(v as RsaHash)} options={hashOptions} className="w-36" />
          </ToolSettings>
          {scheme === 'RSA-PSS' && <p className="-mt-2 text-xs text-muted-foreground">RSA-PSS keys and RSASSA-PKCS1-v1_5 keys share the same PEM format, but the scheme must match when verifying. PSS salt length = hash length.</p>}
          <ToolInput label="Message" value={msg} onChange={setMsg} rows={4} emptyHint="Type the message to sign." mono={false} />
          <ToolActions><Button variant="primary" disabled={busy || !priv || !msg} onClick={() => exec(async () => setResult(await rsaSign(priv, scheme, hash, msg)))}><PenLine /> Sign</Button></ToolActions>
          <ToolOutput label="Signature (Base64)" value={result} error={error} errorTitle="Unable to sign" onClear={reset} wrapLong filename="signature.txt" />
        </>
      )}

      {tab === 'verify' && (
        <>
          <Notice title="Verification (public key)">Verification checks that the signature was produced by the matching private key over exactly this message.</Notice>
          <KeyField label="Public key" value={pub} onChange={setPub} placeholder="-----BEGIN PUBLIC KEY-----" />
          <ToolSettings>
            <Select label="Scheme" value={scheme} onChange={(v) => setScheme(v as RsaSignScheme)} options={[{ value: 'RSA-PSS', label: 'RSA-PSS' }, { value: 'RSASSA-PKCS1-v1_5', label: 'RSASSA-PKCS1-v1_5' }]} className="w-56" />
            <Select label="Hash" value={hash} onChange={(v) => setHash(v as RsaHash)} options={hashOptions} className="w-36" />
          </ToolSettings>
          <ToolInput label="Message" value={msg} onChange={setMsg} rows={3} emptyHint="Type the original message." mono={false} />
          <ToolInput label="Signature (Base64)" value={sig} onChange={setSig} rows={3} emptyHint="Paste the Base64 signature." />
          <ToolActions><Button variant="primary" disabled={busy || !pub || !msg || !sig} onClick={() => exec(async () => setVerdict(await rsaVerify(pub, scheme, hash, msg, sig.trim())))}><ShieldCheck /> Verify</Button></ToolActions>
          {error && <ErrorMessage title="Unable to verify">{error}</ErrorMessage>}
          {verdict !== null && (verdict
            ? <div role="status" className="rounded-lg border border-success/40 bg-success/10 p-4 text-sm font-medium text-success">Signature is valid for this message and public key.</div>
            : <div role="status" className="rounded-lg border border-danger/40 bg-danger/10 p-4 text-sm font-medium text-danger">Signature is NOT valid. The message, signature, key, scheme or hash does not match.</div>)}
        </>
      )}
    </>
  )
}
